service: math_solver_app

image: kyulyak/math_solver_app

builder:
  arch: amd64

servers:
  web:
    - 93.183.82.13

proxy:
  ssl: false
  host: 93.183.82.13

registry:
  username: kyulyak
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: math_solver_app-db
    POSTGRES_USER: math_solver_app
    POSTGRES_DB: math_solver_app_production
    RAILS_ENV: production
  secret:
    - SECRET_KEY_BASE
    - POSTGRES_PASSWORD

accessories:
  db:
    image: postgres:16
    host: 93.183.82.13
    env:
      clear:
        POSTGRES_USER: math_solver_app
        POSTGRES_DB: math_solver_app_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data